doctrine_migrations:
    migrations_paths:
        DoctrineMigrations: '%kernel.project_dir%/app/migrations'
    storage:
        table_storage:
            table_name: 'migration_versions'
    enable_profiler: '%kernel.debug%'
