draw_open_api:
    openApi:
        schema:
            info:
                title: "test"

        definitionAliases:
            -   class: 'App\Entity\'
                alias: ''
            -   class: 'App\DTO\'
                alias: ''
