sonata_admin:
    templates:
        user_block: '@DrawUser/Sonata/Block/user_block.html.twig'

sonata_block:
    blocks:
        Draw\Bundle\UserBundle\Sonata\Block\UserCountBlock: ~

draw_user:
    sonata: ~

    jwt_authenticator:
        key: 'acme'

framework:
    messenger:
        routing:
            Draw\Bundle\UserBundle\Message\ResetPassword: 'draw'
            Draw\Bundle\UserBundle\Message\AutoConnect: 'draw'
